version: '3'

services:
  backend:
    container_name: backend
    image: 20041128/collections:0.0.1
    env_file:
      - .env
    expose:
      - '3000' 

  caddy:
    container_name: caddy
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:
